version: '3.4'

services:
  courses_backend:
    image: otus-backend
    build: ./otus-django
    volumes:
      - media:/opt/otus-django/otus-courses-website/media
    environment:
      - DEBUG=True
      - ALLOWED_HOSTS=0.0.0.0

  proxy:
    image: nginx-proxy
    build: ./nginx-proxy
    ports:
      - "80:8000"
    volumes:
      - media:/opt/media
    depends_on:
      - courses_backend

volumes:
  media:
